from __future__ import annotations

import csv
import re
import subprocess
from pathlib import Path
from zipfile import ZipFile

from docx import Document


ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs" / "manuscript_development"
OUTPUTS = ROOT / "outputs_local"
ASSETS = OUTPUTS / "docs" / "manuscript_development" / "generated_assets"
PACKAGE = OUTPUTS / "docs" / "manuscript_development" / "package_outputs" / "CO2_rSO2_manuscript_development_package.zip"
REPORT = DOCS / "CO2_MANUSCRIPT_PACKAGE_QA_REPORT.md"


DOCX_FILES = [
    "CO2_MANUSCRIPT_DRAFT_V1.docx",
    "CO2_SUPPLEMENTARY_METHODS_DRAFT.docx",
    "CO2_SUPPLEMENTARY_TABLES_INDEX.docx",
]

TABLE_FILES = [
    ASSETS / "table1_cohort_characteristics.csv",
    ASSETS / "table2_clinical_step_contrasts.csv",
    ASSETS / "supplementary_etable1_2_cohort_characteristics_long.csv",
    ASSETS / "supplementary_model_diagnostics.csv",
]

EXPECTED_ZIP_ENTRIES = [
    "PACKAGE_MANIFEST.md",
    "main/CO2_MANUSCRIPT_DRAFT_V1.docx",
    "supplement/CO2_SUPPLEMENTARY_METHODS_DRAFT.docx",
    "supplement/CO2_SUPPLEMENTARY_TABLES_INDEX.docx",
    "documentation/CO2_NATURE_STYLE_READINESS_AUDIT.md",
]


def git_value(*args: str) -> str:
    try:
        return subprocess.check_output(["git", *args], cwd=ROOT, text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        return "unavailable"


def count_csv_rows(path: Path) -> tuple[int, int]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        rows = list(csv.reader(f))
    if not rows:
        return 0, 0
    return max(len(rows) - 1, 0), len(rows[0])


def inspect_docx(path: Path) -> dict[str, str]:
    doc = Document(path)
    text = "\n".join(p.text for p in doc.paragraphs)
    with ZipFile(path) as zf:
        zip_status = zf.testzip() or "ok"
    return {
        "paragraphs": str(len(doc.paragraphs)),
        "tables": str(len(doc.tables)),
        "figures": str(len(doc.inline_shapes)),
        "words": str(len(text.split())),
        "bracket_placeholders": str(text.count("[")),
        "display_placeholders": str(len(re.findall(r"\[Insert (?:Table|Figure)", text))),
        "zip_status": zip_status,
    }


def source_placeholder_counts() -> dict[str, int]:
    text = (DOCS / "CO2_MANUSCRIPT_DRAFT_V1.md").read_text(encoding="utf-8")
    return {
        "display_placeholders": len(re.findall(r"\[Insert (?:Table|Figure)", text)),
        "author_regulatory_placeholders": len(
            re.findall(r"\[(?:Use|Confirm|To calculate|Insert the confirmed|Insert contribution|Insert acknowledgements)", text)
        ),
    }


def render_counts() -> dict[str, int]:
    qa_dir = OUTPUTS / "docs" / "manuscript_development" / "render_qa"
    return {
        "main_review_ready": len(list((qa_dir / "main_review_ready").glob("page-*.png"))),
        "supp_methods_review_ready": len(list((qa_dir / "supp_methods_review_ready").glob("page-*.png"))),
        "supp_tables_review_ready_v3": len(list((qa_dir / "supp_tables_review_ready_v3").glob("page-*.png"))),
    }


def package_status() -> tuple[str, list[str], list[str], list[str]]:
    if not PACKAGE.exists():
        return "missing", [], EXPECTED_ZIP_ENTRIES, []
    with ZipFile(PACKAGE) as zf:
        bad = zf.testzip()
        names = zf.namelist()
        manifest = zf.read("PACKAGE_MANIFEST.md").decode("utf-8").splitlines()[:8]
    missing = [name for name in EXPECTED_ZIP_ENTRIES if name not in names]
    status = "ok" if bad is None else f"bad entry: {bad}"
    return status, names, missing, manifest


def build_report() -> str:
    commit = git_value("rev-parse", "--short", "HEAD")
    branch = git_value("branch", "--show-current")
    dirty = "yes" if git_value("status", "--short") else "no"
    package_zip_status, package_names, package_missing, manifest_head = package_status()
    md_counts = source_placeholder_counts()
    renders = render_counts()

    lines = [
        "# CO2-rSO2 Manuscript Package QA Report",
        "",
        "Generated by `docs/manuscript_development/check_manuscript_package.py`.",
        "",
        f"Git branch: `{branch}`",
        f"Git commit: `{commit}`",
        f"Working tree dirty at QA generation: `{dirty}`",
        "",
        "## DOCX Structure",
        "",
        "| File | ZIP test | Paragraphs | Tables | Figures | Words | Bracket placeholders | Display placeholders |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for name in DOCX_FILES:
        row = inspect_docx(DOCS / name)
        lines.append(
            f"| `{name}` | {row['zip_status']} | {row['paragraphs']} | {row['tables']} | "
            f"{row['figures']} | {row['words']} | {row['bracket_placeholders']} | {row['display_placeholders']} |"
        )

    lines.extend(
        [
            "",
            "## Markdown Source Placeholders",
            "",
            "| Placeholder class | Count | Interpretation |",
            "| --- | ---: | --- |",
            (
                f"| Display-item placeholders in Markdown source | {md_counts['display_placeholders']} | "
                "Expected: the DOCX builder replaces these with embedded tables and figures. |"
            ),
            (
                f"| Author/regulatory placeholders in Markdown source | {md_counts['author_regulatory_placeholders']} | "
                "Expected hard stops until author-side details are confirmed. |"
            ),
            "",
            "## Table Assets",
            "",
            "| Asset | Data rows | Columns |",
            "| --- | ---: | ---: |",
        ]
    )
    for path in TABLE_FILES:
        rows, cols = count_csv_rows(path)
        lines.append(f"| `{path.relative_to(ROOT).as_posix()}` | {rows} | {cols} |")

    lines.extend(
        [
            "",
            "## Render QA Intermediates",
            "",
            "Rendered PNG/PDF files are local QA intermediates and are intentionally ignored by git.",
            "",
            "| Render set | PNG pages present locally |",
            "| --- | ---: |",
        ]
    )
    for name, count in renders.items():
        lines.append(f"| `{name}` | {count} |")

    lines.extend(
        [
            "",
            "## Package ZIP",
            "",
            f"ZIP status: `{package_zip_status}`",
            f"ZIP entries: `{len(package_names)}`",
            f"Missing expected entries: `{', '.join(package_missing) if package_missing else 'none'}`",
            "",
            "Manifest header:",
            "",
            "```text",
            *manifest_head,
            "```",
            "",
            "## Remaining Hard Stops",
            "",
            "- Confirm author list, author order, affiliations, ORCID identifiers, and correspondence.",
            "- Confirm ethics approval, consent or waiver wording, study dates, and parent-cohort wording.",
            "- Confirm funding, competing interests, author contributions, acknowledgements, data availability, and code availability.",
            "- Decide whether to complete the planned 5-model sensitivity analyses before submission.",
            "- Apply target-journal reference style, figure naming, source-data naming, and supplementary workbook tab names.",
            "",
            "## QA Judgment",
            "",
            "The package is review-ready if DOCX ZIP tests are ok, the main DOCX has 2 tables and 3 main figures, display placeholders are absent from the DOCX, and the package ZIP contains the expected manuscript, supplement, audit, and manifest entries.",
            "",
            "The package is not final submission-ready while author-side statements, ethics/funding declarations, sensitivity-analysis choice, and target-journal formatting remain unresolved.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    report = build_report()
    REPORT.write_text(report, encoding="utf-8")
    print(REPORT)


if __name__ == "__main__":
    main()
